baseURL = "https://b00g.com"
languageCode = "en-us"
title = "Dick Hogle"

relativeURLs = true
theme = ["borialis", "hugo-shortcode-gallery"]

timeout = "600"

disableKinds = ["taxonomy", "taxonomyTerm"]
